import React, { useEffect } from 'react'
import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import CategoryCard from '../../../components/Admin/CategoryCard'
import Head from 'next/head'
import Layout from '../../../components/Layout'
import AdminHeader from '../../../components/Admin/Header'
import OfferCards from '../../../components/Admin/OfferCards'
import { useModal } from '../../../shared/hooks/useModal'
import AdminModal from '../../../components/UI/AdminModal'
import { NextPage } from 'next'
import { useGlobalContext } from '../../../Context/GlobalContext'
import { useTranslation } from 'react-i18next'

const AdminOffers:NextPage = () => {
  const {t}=useTranslation()

  const {isOpen,open,close}=useModal()
  const{formComponent,setFormComponent,isAdmin,setIsAdmin}=useGlobalContext() || {}
  useEffect(() => {
    const storedIsAdmin = localStorage.getItem('isAdmin');
    // const storedIsAdmin = sessionStorage.getItem('isAdmin');

    setIsAdmin(storedIsAdmin === 'true');
  }, []);

  return (
    <>
    {isAdmin? ( <div>
        <Head>
        <title>Offer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
      >
        <AdminModal modalType="addOffer" formm={formComponent} modalTitle={t('Add Offer')} modalDescription={t("Add your offer infarmation")} btnText={t("Create Offer")} onClose={close} isOpen={isOpen}  />
      <AdminHeader
      />
      <div className='flex'>
        <div className='hidden lg:block'>
      <SideBar/>
      </div>
      <div className='lg:flex-col w-full pe-4 lg:pe-0 me-4'>
      <TopDiv addButton onClick={open} title={t("Offers")} btnText={t("ADD OFFER")}/>
      <div className='flex gap-5 ms-4 lg:ms-0'>
      <OfferCards
      />
      </div>
      </div>
      </div>
      </Layout>

    </div>) :(<>this page for admin</>)}
   
    </>
  )
}

export default AdminOffers
