import React from 'react'
import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import CategoryCard from '../../../components/Admin/CategoryCard'
import Head from 'next/head'
import Layout from '../../../components/Layout'
import AdminHeader from '../../../components/Admin/Header'
import OrderCards from '../../../components/Admin/OrderCards'
import OfferCards from '../../../components/Admin/OfferCards'

const AdminOffers = () => {
  return (
    <div>
        <Head>
        <title>Offer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
      >
      <AdminHeader
      />
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv addButton  title="Offers" btnText="ADD OFFER"/>
      <div className='flex gap-5 flex-wrap'>
      <OfferCards
      />
      </div>
      </div>
      </div>
      </Layout>

    </div>
  )
}

export default AdminOffers
