import React, { useEffect, useState } from 'react'
import SideBar from '../../../components/Admin/SideBar'
import Head from "next/head";
import AdminHeader from '../../../components/Admin/Header';
import ProductCards from '../../../components/Admin/ProductCards';
import TopDiv from '../../../components/Admin/TopDiv';
import Layout from '../../../components/Layout';
import DeleteModal from '../../../components/Modals/DeleteModal';
import { useModal } from '../../../shared/hooks/useModal';
import { NextPage } from 'next';
import { useGlobalContext } from '../../../Context/GlobalContext';
import { useTranslation } from 'react-i18next';
import { BarLoader, CircleLoader, ClipLoader, GridLoader } from 'react-spinners';



 




const AdminProducts:NextPage = () => {
  // const {isOpen,open,close}=useModal()

const { isAdmin, setIsAdmin,productsData,selectedId ,isLoading,idForFilter,setIdForFilter} = useGlobalContext()|| {}
const {t}=useTranslation()

 
useEffect(() => {
  // const storedIsAdmin = localStorage.getItem('isAdmin');
  const storedIsAdmin = sessionStorage.getItem('isAdmin');

  setIsAdmin(storedIsAdmin === 'true');
}, []);
const [showProducts,setShowProducts]=useState<any[]>([])
const [showFilteredProducts,setShowFilteredProducts]=useState<any[]>([])
console.log("topdivde selectedidddddddddddddddddddddddddddddddd",idForFilter);



const filteredProducts=productsData?.filter((product)=>product.rest_id===idForFilter)
console.log("topdivde selectedidddd proddddddddd",filteredProducts);

useEffect(() => {
  if (productsData) {
    setShowProducts(productsData);
  }
}, []);
useEffect(() => {
  if (idForFilter) {
    setShowFilteredProducts(filteredProducts || []);
  }
}, [idForFilter, filteredProducts]);


// if (isLoading ) {
//   return <div className=' w-full h-screen fixed  justify-center items-center flex m-auto bg-black'>    <CircleLoader color="#36D7B7" loading={true} />
// </div>;
//   }
 
  return (
    <div>
      {isAdmin ? (<>       <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <AdminHeader/>
      <div className='flex'>
<div className='hidden lg:block' >
      <SideBar/>
      </div>
      <div className='flex flex-col w-full me-4'>

      <TopDiv select selectText={t("Restuarant type")} title={t("Products")} />

      <div className=' m-auto lg:m-0 lg:flex lg:gap-5 flex-wrap'>
    

{(idForFilter ? showFilteredProducts : showProducts)?.map((product)=>(

<ProductCards key={product.id} product={product}/>

        ))}
        


      

      </div>
      </div>
      </div>
      </Layout></>): (<>this page for admin</>)}
 

    </div>
  )
}

export default AdminProducts
