import Head from 'next/head'
import React from 'react'
import MainClient from '../../components/Client/MainClient'
import RedHeader from '../../components/Client/RedHeader'
import Image from 'next/image'

const LoginPage = () => {
  return (
    <div>
   <>
   <Head>
        <title>Login|Desktop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <MainClient>
<RedHeader/>
<div className='flex  mt-7 '>

    <div className='leftt w-2/3 bg-mainRed rounded-[4px]'>
        <Image width={1000} height={1000} src="/pngs/member.svg" alt='png'/>
    </div>
    <div className='rightt w-1/2 flex flex-col px-10 '>
        <div>
<div className='flex mt-24 mb-[72px] gap-[65px] justify-center'>
    <button className=' text-mainRed font-roboto  font-[600] text-[30px] letter3'>Login</button>
    <button className='  text-par3-text font-roboto  font-[400] text-[30px] letter3'>Register</button>
</div>
<form action="submit">
    <label className=' text-modal_p text-[20px] font-[500] ' htmlFor="">Username</label>
    <input className=' font-roboto font-[400] text-modal_p h-[68px] w-full mb-7 bg-lightPink  mt-4 ps-6 rounded-[5px]  text-[18px]  ' type="text" placeholder='username' />

    <label className=' text-modal_p  text-[20px] font-[500] ' htmlFor="">Password</label>
    <input className=' font-roboto font-[400] text-modal_p h-[68px] w-full bg-lightPink  mt-4 ps-6 rounded-[5px]  text-[18px]  ' type="password" placeholder='password'/>
<button className='mt-[72px] bg-mainRed h-[68px] w-full text-white rounded-[5px] text-[22px]' type="submit">Log in</button>
</form>
</div>
    </div>
</div>
   </MainClient>
   </>
    </div>
  )
}

export default LoginPage
