import Head from 'next/head'
import React from 'react'
import MainClient from '../../../components/Client/MainClient'
import HeaderClient from '../../../components/Client/HeaderClient'
import UserSidebar from '../../../components/Client/UserSidebar'
import UsersProfile from '../../../components/Client/UsersProfile'
import FooterClient from '../../../components/Client/FooterClient'

const UserProfile = () => {
  return (
    <>
    <div>
      <Head>
<title>User</title>
<meta name='description '  content="Generated by next create app"/>

      </Head>
      <MainClient>


        <HeaderClient/>

        <div className='mt-4 flex gap-4 mb-[186px]'>
           <UserSidebar/> 
           <UsersProfile/>
        </div>
      </MainClient>
      <FooterClient/>
    </div>
    </>
  )
}

export default UserProfile
