import type { NextPage } from "next";
import Head from "next/head";

import Chart from 'chart.js/auto';
import DoughnutChart from "../../components/Admin/Charts/ChartMonths";
import SideBar from "../../components/Admin/SideBar";
import ChartSalary from "../../components/Admin/Charts/ChartSalary";
import AdminHeader from "../../components/Admin/Header";
import AdminModal from "../../components/UI/AdminModal";
import Layout from "../../components/Layout";
import FormAddRestuarant from "../../components/UI/FormAddProducts";

const AdminDashboard: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Layout>
  <AdminHeader/>
  <div className="flex">
  <div className="flex">
    <SideBar/>
    
    
  </div>
<div className=" bg-dark-div w-[472px] h-[472px] flex flex-col mt-5 rounded-[14px] ">
<div className="flex flex-col m-auto">
  <div>
    <p className=" text-par-text">Orders</p>
  </div>
      <DoughnutChart  />
      </div>
      <div className=" overflow-y-auto">
      <AdminModal Restform/>
       
      </div>

      </div>

      <div className=" bg-dark-div w-[634px] h-[472px] flex flex-col  rounded-[14px] m-5 ">
<div className="flex flex-col m-auto">
  <div>
    <p className=" text-par-text">Total Salary</p>
  </div>
      </div>
     

      </div>
   
      </div>
      </Layout>

    </div>
  );
};

export default AdminDashboard;
