import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import MainClient from '../../../components/Client/MainClient'
import HeaderClient from '../../../components/Client/HeaderClient'
import UserSidebar from '../../../components/Client/UserSidebar'
import UserOrderCard from '../../../components/Client/UserOrderCard'
import FooterClient from '../../../components/Client/FooterClient'
import { useGlobalContext } from '../../../Context/GlobalContext'

const UserOrders = () => {

const{   userOrdersData,isLoading}=useGlobalContext() || {}

if(isLoading){

  return <div>yuklenir hele</div>
}


  return (
    <div>
      <Head>
        <title>Your Orders</title>
        <meta name='description'  content='Generated by next create app'/>
      </Head>
      <MainClient>
        <HeaderClient/>
        <div className='mt-4 flex gap-4'>
            <UserSidebar/>
            <UserOrderCard  />

        </div>
      </MainClient>
      <FooterClient/>
    </div>
  )
}

export default UserOrders
