import React, { useEffect } from 'react'
import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import CategoryCard from '../../../components/Admin/CategoryCard'
import Head from 'next/head'
import Layout from '../../../components/Layout'
import AdminHeader from '../../../components/Admin/Header'
import OrderCards from '../../../components/Admin/OrderCards'
import { NextPage } from 'next'
import { useGlobalContext } from '../../../Context/GlobalContext'
import { divider } from '@nextui-org/react'
import { useTranslation } from 'react-i18next'

const AdminOrders:NextPage = () => {

const {isAdmin,setIsAdmin}=useGlobalContext() ||{}

useEffect(() => {
  const storedIsAdmin = localStorage.getItem('isAdmin');
  setIsAdmin(storedIsAdmin === 'true');
}, []);
const {t}=useTranslation()

  return (
    <div>
      {isAdmin ? (<>       <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
      >
      <AdminHeader
      />
      <div className='flex'>
        <div className='hidden lg:block' >
      <SideBar/>
      </div>
      <div className=' lg:flex-col w-full pe-4 lg:pe-0 me-4'>
      <TopDiv   title={t("Orders")}/>
      <div className='flex gap-5 ms-4 lg:ms-0  '>
      <OrderCards

      />
      </div>
      </div>
      </div>
      </Layout>
</>): (<></>)}
 
    </div>
  )
}

export default AdminOrders
