import React, { useEffect } from 'react'
import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import CategoryCard from '../../../components/Admin/CategoryCard'
import Head from 'next/head'
import Layout from '../../../components/Layout'
import AdminHeader from '../../../components/Admin/Header'
import OrderCards from '../../../components/Admin/OrderCards'
import { NextPage } from 'next'
import { useGlobalContext } from '../../../Context/GlobalContext'
import { divider } from '@nextui-org/react'

const AdminOrders:NextPage = () => {

const {isAdmin,setIsAdmin}=useGlobalContext() ||{}

useEffect(() => {
  const storedIsAdmin = localStorage.getItem('isAdmin');
  setIsAdmin(storedIsAdmin === 'true');
}, []);

  return (
    <div>
      {isAdmin ? (<>       <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
      >
      <AdminHeader
      />
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv   title="Orders"/>
      <div className='flex gap-5 flex-wrap'>
      <OrderCards

      />
      </div>
      </div>
      </div>
      </Layout>
</>): (<></>)}
 
    </div>
  )
}

export default AdminOrders
