import Head from 'next/head'
import React, { useState } from 'react'
import AdminHeader from '../../../components/Admin/Header'
// import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import AddButton from '../../../components/Admin/AddButton'
import RestuarantCards from '../../../components/Admin/RestuarantCards'
import Layout from '../../../components/Layout'
import SideBar from '../../../components/Admin/SideBar'
import AdminModal from '../../../components/UI/AdminModal'
import { useModal } from '../../../shared/hooks/useModal'
import { NextPage } from 'next'
import { useGlobalContext } from '../../../Context/GlobalContext'


const Restuarants:NextPage = () => {
  const {isOpen,open,close}=useModal()
  const{formComponent,setFormComponent}=useGlobalContext() || {}

  return (

    <div>
        <Head>
        <title>Restuarants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
     <AdminModal  formm={formComponent} modalTitle='Add Restuarant' modalDescription="
Add your Restuarants information"btnText="Create Restuarant" isOpen={isOpen} onClose={close} />
      <AdminHeader/>
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv addButton onClick={open} select title="Restuarants" btnText="ADD RESTUARANT" selectText="Category type"/>
      <div className='flex gap-5 flex-wrap'>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
    
      <RestuarantCards/>
      <RestuarantCards/>

      </div>
      </div>
      </div>
      </Layout>

    </div>
  )
}

export default Restuarants
