import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import AdminHeader from '../../../components/Admin/Header'
// import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import AddButton from '../../../components/Admin/AddButton'
import RestuarantCards from '../../../components/Admin/RestuarantCards'
import Layout from '../../../components/Layout'
import SideBar from '../../../components/Admin/SideBar'
import AdminModal from '../../../components/UI/AdminModal'
import { useModal } from '../../../shared/hooks/useModal'
import { NextPage } from 'next'
import { useGlobalContext } from '../../../Context/GlobalContext'


const Restuarants:NextPage = () => {
  const {isOpen,open,close}=useModal()
  const{formComponent,setFormComponent,restaurantData,isAdmin,setIsAdmin,selectedId,idForFilter,setIdForFilter}=useGlobalContext() || {}
  const [showRestaurant,setShowRestaurant]=useState<any[]>([])
  const [showFilteredRestaurant,setShowFilteredRestaurant]=useState<any[]>([])
  useEffect(() => {
    const storedIsAdmin = localStorage.getItem('isAdmin');
    setIsAdmin(storedIsAdmin === 'true');
  }, []);
 useEffect(()=>{
if(restaurantData){
  setShowRestaurant(restaurantData)

}

 },[restaurantData])
const filteredRestaurant=restaurantData?.filter((resttaurant)=>resttaurant.category_id===idForFilter)
useEffect(()=>{

  if(idForFilter){  setShowFilteredRestaurant(filteredRestaurant || [])
  }
 },[idForFilter,filteredRestaurant])

  return (

    <div>
      {isAdmin ? (<>      <Head>
        <title>Restuarants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
     <AdminModal modalType="addRestaurant"  formm={formComponent} modalTitle='Add Restuarant' modalDescription="
Add your Restuarants information" btnText="Create Restuarant" isOpen={isOpen} onClose={close} />
      <AdminHeader/>
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv addButton onClick={open} select title="Restuarants" btnText="ADD RESTUARANT" selectText="Category type"/>
      <div className='flex gap-4 flex-wrap'>
        {(idForFilter ? showFilteredRestaurant :showRestaurant)?.map((restaurant)=>(
      <RestuarantCards key={restaurant.id} restaurant={restaurant}/>



      
        ))}
      

      </div>
      </div>
      </div>
      </Layout></>):(<></>)}
  

    </div>
  )
}

export default Restuarants
