import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import MainClient from '../../../components/Client/MainClient'
import HeaderClient from '../../../components/Client/HeaderClient'
import UserSidebar from '../../../components/Client/UserSidebar'
import BasketCard from '../../../components/Client/BasketCard'
import { useGlobalContext } from '../../../Context/GlobalContext'
import { useTranslation } from 'react-i18next'

const UserBasket = () => {
  // const { basketData: initialBasketData ,isUser} = useGlobalContext() || {};
  // const [basketData, setBasketData] = useState(initialBasketData);


  const {basketData,isLoading}=useGlobalContext() || {}
  const { t } = useTranslation()

  if(isLoading){    return <div className='mx-10'>Loading....................</div>
  }

  // useEffect(() => {
  //   if(isUser && initialBasketData){
  //     setBasketData(initialBasketData);

  //   }
    
  // }, [,isUser,initialBasketData]);


  return (
    <div>

        <Head>

       <title>User Basket</title> 
       <meta name="description" content='Generated by next create app'/>    
        </Head>
        <MainClient>
            <HeaderClient/>
            <div className='mt-4  mx-4 lg:mx-0 flex gap-4'>
<div className='hidden lg:block'>
<UserSidebar/>
</div>
<div className='w-full '>
<BasketCard basketData={basketData} size="large" headtitle={t("Your Basket")}/>
</div>
            </div>
        </MainClient>
    </div>
  )
}

export default UserBasket
