import Head from 'next/head'
import React, { useEffect } from 'react'
import MainClient from '../../../components/Client/MainClient'
import HeaderClient from '../../../components/Client/HeaderClient'
import UserSidebar from '../../../components/Client/UserSidebar'
import BasketCard from '../../../components/Client/BasketCard'
import { useGlobalContext } from '../../../Context/GlobalContext'

const UserBasket = () => {
  const {basketData}=useGlobalContext() || {}
  
  return (
    <div>

        <Head>

       <title>User Basket</title> 
       <meta name="description" content='Generated by next create app'/>    
        </Head>
        <MainClient>
            <HeaderClient/>
            <div className='mt-4 flex gap-4'>

<UserSidebar/>
<BasketCard basketData={basketData} size="large" headtitle="Your Basket"/>
            </div>
        </MainClient>
    </div>
  )
}

export default UserBasket
