import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import MainClient from '../../../components/Client/MainClient'
import HeaderClient from '../../../components/Client/HeaderClient'
import UserSidebar from '../../../components/Client/UserSidebar'
import BasketCard from '../../../components/Client/BasketCard'
import { useGlobalContext } from '../../../Context/GlobalContext'
import { useTranslation } from 'react-i18next'
import { divider } from '@nextui-org/react'
import { CircleLoader} from 'react-spinners';

const UserBasket = () => {
 

  const {basketData,isLoading,isUser}=useGlobalContext() || {}
  const { t } = useTranslation()

 
if (isLoading ) {
  return <div className=' w-full h-screen fixed  justify-center items-center flex m-auto bg-black'>    <CircleLoader color="#36D7B7" loading={true} />
</div>;
  }
  
  return (
    <div>
      {isUser ? (<>
        <Head>

<title>User Basket</title> 
<meta name="description" content='Generated by next create app'/>    
 </Head>
 <MainClient>
     <HeaderClient/>
     <div className='mt-4  mx-4 lg:mx-0 flex gap-4'>
<div className='hidden lg:block'>
<UserSidebar/>
</div>
<div className='w-full '>
<BasketCard basketData={basketData} size="large" headtitle={t("Your Basket")}/>
</div>
     </div>
 </MainClient>
      </>):(<div> you are logout</div>)}

      
    </div>
  )
}

export default UserBasket
