import React from 'react'
import MainClient from '../../components/Client/MainClient'
import HeaderClient from '../../components/Client/HeaderClient'
import Head from 'next/head'
import SidebarClient from '../../components/Client/SidebarClient'
import RestaurantCards from '../../components/Client/RestaurantCards'
import FooterClient from '../../components/Client/FooterClient'
import { NextPage } from 'next'

const RestaurantsPage:NextPage = () => {
  return (
    <div>
   <Head>
    
   <title>Register|Desktop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>  
<MainClient>

    <HeaderClient/>

    <div className='flex mt-4'>
<SidebarClient/>

<div className='w-full flex flex-wrap gap-9 pt-2 ps-10'>
    <RestaurantCards/>
    <RestaurantCards/>
    <RestaurantCards/>
    <RestaurantCards/>
    <RestaurantCards/>

</div>

</div>
</MainClient>
     <FooterClient/>
    </div>
  )
}

export default RestaurantsPage
