import Head from 'next/head'
import React from 'react'
import MainClient from '../../components/Client/MainClient'
import HeaderClient from '../../components/Client/HeaderClient'
import Image from 'next/image'
import FooterClient from '../../components/Client/FooterClient'
import { NextPage } from 'next'
import { useAnimatedStyles } from '../../shared/animated/animated'
import { animated, useSpring } from '@react-spring/web'

const AboutUs:NextPage = () => {

  const{springStyles,springStyles2}=useAnimatedStyles()
  return (
    <div>
    <Head>
        <title>About Us</title>
        <meta name='description ' content='Generated by nesxt create app' />
        </Head>  

        <MainClient>

            <HeaderClient/>
<div className='flex mt-[113px]'>
            <div className='ps-[62px] pe-10 w-1/2'>
                <h1 className=' font-mukta font-[600] mb-7 text-[45px] text-inputPlaceholder'>About Us</h1>
                <p className=' text-par3-text roboto-medium text-[20px]'>Lorem ipsum is placeholder text commonly used in the graphic, print, 
                    and publishing industries for previewing layouts and visual mockups
                    .Lorem ipsum is placeholder text commonly used in the graphic, print,
                     and publishing industries for previewing layouts and visual mockups.
                     Lorem ipsum is placeholder text
                     commonly used in the graphic, print, and publishing industries
                      for previewing layouts and visual mockups.
                      </p>
            </div>

            <div className='w-1/2 relative   me-10'>
              <div className='mt-6 '>
                <Image width={1000} height={1000} src="/svgs/about.svg" alt='aboutus'/>
                </div>
                <animated.div style={springStyles2} className="absolute  top-10 right-10">
                <Image className='w-[274px] h-[228px] ' width={1000} height={1000} src="/svgs/abouthamb.svg" alt='aboutus'/>
                </animated.div>
                <animated.div style={springStyles} className="absolute  top-[220px] left-[20px] ">
                <Image className='w-[274px] h-[228px]' width={1000} height={1000} src="/svgs/aboutpizza.svg" alt='aboutus'/>
                </animated.div>

                <animated.div style={springStyles2} className="absolute  top-[312px] right-[10px]">
                <Image  className='   w-[274px] h-[228px]' width={1000} height={1000} src="/svgs/aboutsoup.svg" alt='aboutus'/>
                </animated.div>

                <animated.div style={springStyles} className=" absolute  top-[524px] left-[20px]">
                <Image  className='   w-[274px] h-[228px]' width={1000} height={1000} src="/svgs/aboutcoffee.svg" alt='aboutus'/>
                </animated.div>

            </div>
            </div>
            
        </MainClient>
        <div className='mt-[102px]'>
        <FooterClient/>
        </div>
    </div>
  )
}

export default AboutUs

