import Head from 'next/head'
import React, { useState } from 'react'
import AdminHeader from '../../../components/Admin/Header'
// import SideBar from '../../../components/Admin/SideBar'
import TopDiv from '../../../components/Admin/TopDiv'
import AddButton from '../../../components/Admin/AddButton'
import RestuarantCards from '../../../components/Admin/RestuarantCards'
import Layout from '../../../components/Layout'
import SideBar from '../../../components/Admin/SideBar'
import AdminRight from '../../../components/Admin/AdminRight'


const Restuarants = () => {

  return (
    <div>
        <Head>
        <title>Restuarants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <AdminHeader/>
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv addButton select title="Restuarants" btnText="Add RESTUARANT" selectText="Category type"/>
      <div className='flex gap-5 flex-wrap'>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>
      <RestuarantCards/>

      </div>
      </div>
      </div>
      </Layout>

    </div>
  )
}

export default Restuarants
