import { NextPage } from 'next'
import React, { useEffect } from 'react'
import { useGlobalContext } from '../../../Context/GlobalContext'
import Layout from '../../../components/Layout'
import TopDiv from '../../../components/Admin/TopDiv'
import SideBar from '../../../components/Admin/SideBar'
import AdminHeader from '../../../components/Admin/Header'
import Head from 'next/head'
import OrderCards from '../../../components/Admin/OrderCards'
import HistoryCards from '../../../components/Admin/HistoryCards'
import { useTranslation } from 'react-i18next'

const OrderHistory:NextPage = () => {

  const{isAdmin,setIsAdmin}=useGlobalContext() ||{}
  useEffect(() => {
    // const storedIsAdmin = localStorage.getItem('isAdmin');
    const storedIsAdmin = sessionStorage.getItem('isAdmin');

    setIsAdmin(storedIsAdmin === 'true');
  }, []);
 const {t}=useTranslation()
  return (
    <div>
        {isAdmin ? (<>       <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
      >
      <AdminHeader
      />
      <div className='flex'>
        <div className='hidden lg:block'>
      <SideBar/>
      </div>
      <div className='lg:flex-col w-full pe-4 lg:pe-0 me-4'>
      <TopDiv  title={t("History")}/>
      <div className='flex gap-5 ms-3 lg:ms-0'>
      <HistoryCards/>

      
      </div>
      </div>
      </div>
      </Layout>
</>): (<>this page for only admin
</>)}
    </div>
  )
}

export default OrderHistory
