import React from 'react'
import SideBar from '../../../components/Admin/SideBar'
import AdminHeader from '../../../components/Admin/Header'
import Head from 'next/head'
import Layout from '../../../components/Layout'
import TopDiv from '../../../components/Admin/TopDiv'
import CategoryCard from '../../../components/Admin/CategoryCard'
import { useModal } from '../../../shared/hooks/useModal'
import AdminModal from '../../../components/UI/AdminModal'
import FormAddCategory from '../../../components/UI/FormAddCategory'

const Category = () => {



  const {isOpen,open,close}=useModal()

  return (
    <div>
        <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <AdminModal formm={<FormAddCategory/>} modalTitle='Add Category'  isOpen={isOpen} onClose={close}/>
      <AdminHeader/>
      <div className='flex'>
      <SideBar/>
      <div className='flex flex-col w-full me-4'>
      <TopDiv addButton={{ onClick: open, }}  title="Category" btnText="ADD CATEGORY" selectText="Category type"/>

      <div className='flex gap-5 flex-wrap'>
      <CategoryCard/>
      </div>
      </div>
      </div>
      </Layout>

    </div>
  )
}

export default Category
