import Head from 'next/head'
import React from 'react'
import MainClient from '../../components/Client/MainClient'
import HeaderClient from '../../components/Client/HeaderClient'
import Image from 'next/image'
import FooterClient from '../../components/Client/FooterClient'
import { NextPage } from 'next'
import AnimatedSection from '../../components/AnimatedSection/AnimatedSection'

const HowItWorks:NextPage = () => {
  return (
    <div>
      
      <Head>
        <title>How It Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainClient>
<HeaderClient/>
<div className='flex flex-col items-center px-24 mt-[74px]'>
  <AnimatedSection>
<div className='  flex flex-col items-center'>
    <h1 className=' font-mukta font-[600] text-[35px] lg:text-[45px] text-inputPlaceholder'>How it works</h1>
    <p className='lg:px-8 text-center roboto-medium font-medium  text-par3-text text-base lg:text-xl '>Delivery may be extended during sale periods. Please refer to the checkout page 
        for an updated estimate for your location. Kindly note that once you have placed an order,
         it is no longer possible to modify your order. Taxes and duties are included in all product prices.
         It is possible to place an order with shipment to a different address than your home or billing 
         address
          when paying with a credit card.
         Please note that Klarna payments require that your order is shipped to your 
         registered home address.</p>
</div>
</AnimatedSection>
<div className='mt-[55px] mb-[122px] lg:mb-0  flex justify-center relative w-full '>
    <Image className='hidden lg:block   ' width={1000} height={1000} src="/svgs/howitorange.svg" alt='delivery'/>
    <Image className='block lg:hidden   ' width={1000} height={1000} src="/icons/yellow2.svg" alt='yellow'/>

    <Image className=' absolute top-[50px] lg:top-[-55px]  lg:w-[628px]' width={1000} height={1000} src="/svgs/delivery.svg"  alt='delivery'/>

</div>

</div>

      </MainClient>
     
        <FooterClient/>
    </div>
  )
}

export default HowItWorks
